# Generated by Django 4.2.3 on 2023-08-02 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0003_tag'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='tittle',
            new_name='title',
        ),
    ]
